//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorsBpla.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecture()
        {
            this.UserLectures = new HashSet<UserLecture>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TextCorrect { get; set; }
        public string FilePath { get; set; }
        public string VideoUrl { get; set; }
        public int IdLevelType { get; set; }
    
        public virtual LevelType LevelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLecture> UserLectures { get; set; }
    }
}
