//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorsBpla.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLecture
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdLecture { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual User User { get; set; }
    }
}
